spring:
  jpa:
    show-sql: false
    open-in-view: false
    database-platform: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/httpqueue
    username: local
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true



