name: Create and publish a Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  GIT_ACTOR: ${{ github.actor }}
  GIT_REPOSITORY: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: downcase ACTOR
        run: |
          echo "ACTOR=${GIT_ACTOR,,}" >>${GITHUB_ENV}
          
      - name: downcase IMAGE_NAME
        run: |
          echo "IMAGE_NAME=${GIT_REPOSITORY,,}" >>${GITHUB_ENV}
          
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Gradle Build Image
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            bootBuildImage
             -Ddocker.publisgRegistry.username=${{ env.ACTOR }}
             -Ddocker.publishRegistry.password=${{ secrets.GITHUB_TOKEN }}
             -Ddocker.publishRegistry.url=${{ env.REGISTRY }}           
             --imageName=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
             -DskipTests
             
      - name: Docker image push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
             
     


